### ISSUE TITLE
Who is working on the accumulated GDD for 3 cities task?

### ISSUE THREAD

**Issue by djo504** [fsfrazao/DegDay#9]

**Comment by fsfrazao** [comment]
Do you mean **task 4.Create plots showing accumulated GDD vs time for selected cities***?

I've done that. The code is in the plot_cummulative_GDD.py program

**Comment by djo504** [comment]
@fsfrazao how do i get the csv files for the accumulated gdd of the stations on my map from your code? Or any station I desire. Thank you

**Comment by djo504** [comment]
@fsfrazao if you look at task two sample plot, you will see that the color map has accumulated gdd probably for range of same years on that map from 1800 to 600. Now looking at the code that i have so far, what do you think is the easiest way to bring in the data to be plotted if you have an idea?
